export const ROUTE_LOGIN = "@route/LOGIN";
export const ROUTE_SIGNUP = "@route/SIGNUP";
export const ROUTE_HOME = "@route/HOME";
export const ROUTE_CHOOSE_DEVICES = "@route/ROUTE_CHOOSE_DEVICES";
export const ROUTE_ABOUT_US = "@route/ROUTE_ABOUT_US";
export const ROUTE_SUPPORT = "@route/ROUTE_SUPPORT";
export const ROUTE_CONTACT_US = "@route/ROUTE_CONTACT_US";
export const ROUTES_STATUS_TRACKING = "@route/ROUTES_STATUS_TRACKING";
export const ROUTES_SHIPPING_STATUS = "@route/ROUTES_SHIPPING_STATUS";
export const ROUTES_GET_QUOTE = "@route/ROUTES_GET_QUOTE";
export const ROUTE_GET_QUOTE_PHONE = "@route/ROUTE_GET_QUOTE_PHONE";
export const ROUTE_GET_QUOTE_LAPTOP = "@route/ROUTE_GET_QUOTE_LAPTOP";
export const ROUTE_GET_QUOTE_WATCH = "@route/ROUTE_GET_QUOTE_WATCH";
export const ROUTES_DEVICE_CONDITION = "@route/ROUTES_DEVICE_CONDITION";
export const ROUTE_PHONE_DEVICE_CONDITION =
  "@route/ROUTE_PHONE_DEVICE_CONDITION";
export const ROUTE_TABLET_DEVICE_CONDITION =
  "@route/ROUTE_TABLET_DEVICE_CONDITION";
export const ROUTE_WATCH_DEVICE_CONDITION =
  "@route/ROUTE_WATCH_DEVICE_CONDITION";
export const ROUTES_SHIPPING_INFO = "@route/ROUTES_SHIPPING_INFO";
export const ROUTES_CONFIRM_TRADE = "@route/ROUTES_CONFIRM_TRADE";
export const ROUTES_SUCCESS_PAGE = "@route/ROUTES_SUCCESS_PAGE";
export const ROUTES_THANKYOU_PAGE = "@route/ROUTES_THANKYOU_PAGE";
export const ROUTES_TRANSACTION_EXPIRED = "@route/ROUTES_TRANSACTION_EXPIRED";
export const ROUTES_TERMS_CONDITION = "@route/ROUTES_TERMS_CONDITION";
export const ROUTES_PRIVACY_POLICY = "@route/ROUTES_PRIVACY_POLICY";
export const VERIFY_TRANSACTION_ERROR = "@route/VERIFY_TRACNSACTION_ERROR";
export const OFFER_ACCEPTED = "@route/OFFER_ACCEPTED";
export const OFFER_DECLINED = "@route/OFFER_DECLINED";
export const ROUTE_ERROR_400 = "@route/ERROR_400";
export const ROUTE_ERROR_403 = "@route/ERROR_403";
export const ROUTE_ERROR_404 = "@route/ERROR_404";
export const ROUTE_ERROR_500 = "@route/ERROR_500";
export const ROUTE_ERROR_502 = "@route/ERROR_502";
export const ROUTE_ERROR_503 = "@route/ERROR_503";
